site_name: "olinkWrapper"
site_author: Jyotirmoy Das
site_description: "A Shiny app for Olink data analysis"
site_url: "https://jd2112.github.io/ShinyOlink"
repo_url: "https://github.com/JD2112/ShinyOlink"
theme:
  name: material
  custom_dir: docs/overrides
  palette:
    primary: blue grey
    accent: blue
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
    - navigation.tabs
    - search.suggest
    - search.highlight
    - toc.integrate
    - content.action.edit
    - content.code.copy
    - versioning
    - icons

plugins:
  - search
  - mike

markdown_extensions:
  - admonition
  - abbr
  - attr_list  
  - pymdownx.details  
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.arithmatex:
      generic: true
  - codehilite
  - toc:
      permalink: true     
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Home: index.md
  - Manual : chapter1.md
  - Olink Proteomics: chapter2.md
  - Technical Background: chapter3.md
  - FAQs: chapter4.md
  # - Chapter 5: chapter5.md
  # - Chapter 6: chapter6.md
  # - Chapter 7: chapter7.md
  # - Chapter 8: chapter8.md

extra:
  version:
    provider: mike
  current_year: !!python/object/apply:str ["2025"]

extra_css:
  - styles/extra.css

extra_javascript:
  - https://fonts.googleapis.com/css2?family=Fira+Code&family=Inter:wght@400;600&display=swap
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-MML-AM_CHTML